apiVersion: storage.k8s.io/v1
kind: CSINode
metadata:
  annotations:
    storage.alpha.kubernetes.io/migrated-plugins: kubernetes.io/aws-ebs,kubernetes.io/azure-disk,kubernetes.io/azure-file,kubernetes.io/cinder,kubernetes.io/gce-pd,kubernetes.io/vsphere-volume
  creationTimestamp: "2024-09-17T14:28:25Z"
  name: aks-agentpool-20055813-vmss000005
  ownerReferences:
  - apiVersion: v1
    kind: Node
    name: aks-agentpool-20055813-vmss000005
    uid: e6cd5def-b1e3-46f7-8c4d-b226ff3b509c
  resourceVersion: "2627670"
  uid: 94452f2c-3a47-43e2-84f8-016c859f94b4
spec:
  drivers:
  - name: secrets-store.csi.k8s.io
    nodeID: aks-agentpool-20055813-vmss000005
    topologyKeys: null
  - name: file.csi.azure.com
    nodeID: aks-agentpool-20055813-vmss000005
    topologyKeys: null
  - allocatable:
      count: 4
    name: disk.csi.azure.com
    nodeID: aks-agentpool-20055813-vmss000005
    topologyKeys:
    - topology.disk.csi.azure.com/zone
